<a href="https://colab.research.google.com/github/VitorMirandaAquino/pucrio-mvp-analise-dados/blob/main/MVP_An%C3%A1lise_de_Dados_e_Boas_Pr%C3%A1ticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MVP Machine Learning & Analytics

**Nome:** Vitor Miranda de Aquino

**Matrícula:** 4052025001191

**Dataset:** [HR Analytics Dataset](https://www.kaggle.com/datasets/saadharoon27/hr-analytics-dataset)

# Sumário

1. [Descrição do Problema](#descricao): Descritivo do problema detalhando o dataset, o problema e as hipóteses criadas
2. [Setup para análise](#setup):  Importação das bibliotecas, funções auxiliares e carga dos dados
3. [Replicação do processamento do MVP anterior](#replicacao):  Replicação dos processos e etapas realizadas no MVP anterior
4. [Comparativo de modelos e processamentos](#comparativo): Comparativo entre os resultados obtidos com os diferentes modelos e processamentos
5. [Otimização de hiperparâmetros](#otimizacao): Otimização dos hiperparâmetros utilizando o melhor pipeline obtido no comparativo de modelos e processamentos
6. [Avaliação do modelo final](#avaliacao): Avaliação dos resultados obtidos com o modelo final
7. [Conclusão das análise](#conclusao): Conclusões obtidas durante o treinamento

# <a id='descricao'>Descrição do Problema</a>

O conjunto de dados **HR Analytics** é um conjunto de dados multivariado que contém informações sobre funcionários de uma empresa, incluindo características demográficas, profissionais e comportamentais. O objetivo principal é analisar e prever a rotatividade de funcionários (attrition) com base em diversas variáveis como idade, salário, tempo de empresa, satisfação no trabalho, distância de casa, entre outras. O problema visa identificar fatores que contribuem para o desligamento de funcionários.

## Hipóteses do Problema

As hipóteses em relação ao **comportamento dos funcionários**:
- O nível de satisfação geral está baixo o que pode levar ao desligamento
- Os funcionários estão precisando viajar muito
- Os funcionários estão precisando fazer muitas horas extras
- Os funcionários estão recebendo poucos benefícios
- Os funcionários não estão conseguindo equilibrar a vida com o trabalho
- Os funcionários estão levando muito anos até serem promovidos
- Os funcionários estão levando muito tempo até chegar ao trabalho

As hipóteses que levam ao **desligamento da empresa**:
- Os funcionários mais novos estão se desligando mais da empresa por um comportamento da nova geração
- Pessoas que precisam de um deslocamento maior para ir trabalhar, também são mais propensas a deixar empresa
- Pessoas com salário menor são propensas a desligar da empresa
- Pessoas com mais tempo de empresa são menos propensas a deixar empresa
- Pessoas que realizam horas extras estão mais propensas a desligar da empresa

## Tipo de Problema

Este é um problema de **classificação supervisionada**. Dado um conjunto de características, o objetivo é prever se o funcionário irá deixar a empresa.

## Seleção de Dados

O dataset de Recursos humanos foi obtido no kaggle e contém diversas informações sobre funcionários de algumas empresas e se eles deixaram a empresa ou não. O dataset vai precisar de uma etapa de pré processamento para eliminar variáveis duplicadas como (Idade e grupo de idade) ou irrelevantes para análise como  "maior de 18 anos" (100% das instâncias são maiores de 18 anos).

## Atributos do Dataset

O dataset **HR Analytics** contém 1480 amostras, com 238 amostras de funcionários que deixaram a empresa e 1242 amostras de funcionários ativos na empresa. Possui 38 atributos:

Formato: **Nome da coluna**: "Tradução" - "Descrição da coluna" - `Tipo da coluna (Inteiro, Float ou String)`

---

- ***EmpID***: "ID do Funcionário" - "Identificador único do funcionário" - `String`
- ***Age***: "Idade" - "Idade do funcionário" - `Inteiro`
- ***AgeGroup***: "Grupo Etário" - "Grupo etário ao qual o funcionário pertence" - `String`
- ***Attrition***: "Rotatividade" - "Status de rotatividade do funcionário (se deixou ou ainda está ativo na organização)" - `String` {"Yes":"Funcionário deixou a empresa", "No":"Funcionário ativo"}
- ***BusinessTravel***: "Viagens a Negócios" - "Frequência de viagens a negócios do funcionário" - `String`
- ***DailyRate***: "Taxa Diária" - "Taxa diária de pagamento do funcionário" - `Inteiro`
- ***Department***: "Departamento" - "Departamento em que o funcionário trabalha" - `String`
- ***DistanceFromHome***: "Distância de Casa" - "Distância em milhas da casa do funcionário ao local de trabalho" - `Inteiro`
- ***Education***: "Educação" - "Nível de educação alcançado pelo funcionário" - `Inteiro`
- ***EducationField***: "Área de Educação" - "Área de educação do funcionário" - `String`
- ***EmployeeCount***: "Identificador de Funcionário" - "Presença ou não do funcionário" - `Inteiro`
- ***EmployeeNumber***: "Número de Funcionários da empresa" - "Número de funcionários da empresa" - `Inteiro`
- ***EnvironmentSatisfaction***: "Satisfação com o Ambiente" - "Nível de satisfação do funcionário com o ambiente de trabalho" - `Inteiro`
- ***Gender***: "Gênero" - "Gênero do funcionário" - `String`
- ***HourlyRate***: "Taxa Horária" - "Taxa horária de pagamento do funcionário" - `Inteiro`
- ***JobInvolvement***: "Envolvimento no Trabalho" - "Nível de envolvimento do funcionário no trabalho" - `Inteiro`
- ***JobLevel***: "Nível do Cargo" - "Nível da posição de trabalho do funcionário" - `Inteiro`
- ***JobRole***: "Função no Trabalho" - "Função do funcionário dentro da organização" - `String`
- ***JobSatisfaction***: "Satisfação no Trabalho" - "Nível de satisfação do funcionário com seu trabalho" - `Inteiro`
- ***MaritalStatus***: "Estado Civil" - "Estado civil do funcionário" - `String`
- ***MonthlyIncome***: "Renda Mensal" - "Renda mensal do funcionário em dólares" - `Inteiro`
- ***SalarySlab***: "Faixa Salarial" - "Categorização da renda mensal em faixas salariais" - `String`
- ***MonthlyRate***: "Taxa Mensal" - "Taxa mensal de pagamento do funcionário" - `Inteiro`
- ***NumCompaniesWorked***: "Número de Empresas Trabalhadas" - "Número de empresas em que o funcionário trabalhou no passado" - `Inteiro`
- ***Over18***: "Maior de 18 Anos" - "Se o funcionário é maior de 18 anos" - `String`
- ***OverTime***: "Horas Extras" - "Se o funcionário trabalha horas extras ou não" - `String`
- ***PercentSalaryHike***: "Percentual de Aumento Salarial" - "Percentual de aumento no salário do funcionário" - `Inteiro`
- ***PerformanceRating***: "Avaliação de Performance" - "Avaliação de performance do funcionário" - `Inteiro`
- ***RelationshipSatisfaction***: "Satisfação com Relacionamentos" - "Nível de satisfação do funcionário com relacionamentos de trabalho" - `Inteiro`
- ***StandardHours***: "Horas Padrão" - "Horas de trabalho padrão para o funcionário" - `Inteiro`
- ***StockOptionLevel***: "Nível de Opções de Ações" - "Nível de opções de ações concedidas ao funcionário" - `Inteiro`
- ***TotalWorkingYears***: "Total de Anos Trabalhados" - "Número total de anos que o funcionário trabalhou" - `Inteiro`
- ***TrainingTimesLastYear***: "Vezes de Treinamento no Último Ano" - "Número de sessões de treinamento frequentadas pelo funcionário no último ano" - `Inteiro`
- ***WorkLifeBalance***: "Equilíbrio Trabalho-Vida" - "Nível de satisfação do funcionário com o equilíbrio trabalho-vida" - `Inteiro`
- ***YearsAtCompany***: "Anos na Empresa" - "Número de anos que o funcionário trabalhou na empresa atual" - `Inteiro`
- ***YearsInCurrentRole***: "Anos no Cargo Atual" - "Número de anos que o funcionário está no cargo atual" - `Inteiro`
- ***YearsSinceLastPromotion***: "Anos Desde Última Promoção" - "Número de anos desde a última promoção do funcionário" - `Inteiro`
- ***YearsWithCurrManager***: "Anos com Gerente Atual" - "Número de anos que o funcionário trabalha com o gerente atual" - `Float`

---

# <a id='setup'>Setup para análise</a>

## Importação das bibliotecas necessárias
Esta seção consolida todas as importações de bibliotecas necessárias para a análise, visualização e pré-processamento dos dados.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import seaborn as sns
from scipy.stats import chi2_contingency
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

## Funções para análise
Nesta seção sera declaradas as funções para as análises do notebook

In [2]:
def funcao_1():
    pass

In [3]:
def funcao_2():
    pass

## Carga de Dados

Esta seção contém o carregamento inicial do dataset.

In [4]:
# Configuração para mostrar todas as colunas do dataset
pd.set_option('display.max_columns', None)

In [5]:
# Carregamento do Dataset
url = "https://raw.githubusercontent.com/VitorMirandaAquino/pucrio-mvp-analise-dados/refs/heads/main/data/HR_Analytics.csv"
df = pd.read_csv(url)

In [6]:
# primeiras linhas
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,SalarySlab,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,1,405,3,Male,54,3,1,Laboratory Technician,3,Single,1420,Upto 5k,25233,1,Y,No,13,3,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,1,411,4,Female,69,2,1,Sales Representative,3,Single,1200,Upto 5k,9724,1,Y,No,12,3,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,1,614,2,Male,69,3,1,Sales Representative,2,Single,1878,Upto 5k,8059,1,Y,Yes,14,3,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,2,Male,73,3,1,Research Scientist,4,Single,1051,Upto 5k,13493,1,Y,No,15,3,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,1,1156,3,Male,80,3,1,Laboratory Technician,3,Single,1904,Upto 5k,13556,1,Y,No,12,3,4,80,0,0,0,3,0,0,0,0.0

# <a id='setup'>Replicação do processamento do MVP Anterior</a>

No MVP anterior foi realiza uma Análise Exploratória de Dados para identificar quais variáveis seriam interessantes ser inclusas no modelo de Machine Learning.
 <Br>
Segue link para notebook abaixo:

---

<a href="https://colab.research.google.com/github/VitorMirandaAquino/pucrio-mvp-machine-learning/blob/main/MVP_MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>